The new structure will include a technical steering committee to direct technical decisions, oversee working group projects and manage contributions, as well as a board of directors that will guide business decisions.

The technical steering committee will be made up of both Node.js and io.js technical communities. In addition, there will be an individual membership class will have representation on the board.

“The Node.js Foundation provides a neutral structure to balance the needs of all constituents in the community: the users, vendors and contributors,” said Jim Zemlin, executive director of the Linux Foundation. “As projects grow to the size of Node.js, they benefit from the neutrality, open governance and community that only a foundation can provide.”



Read more: http://sdtimes.com/node-js-foundations-open-governance-structure-and-bing-to-use-https-by-default-sd-times-news-digest-june-16-2015/#ixzz3dQG20glE 
Follow us: @sdtimes on Twitter | sdtimes on Facebook


== Doo

[discrete] 
== Discrete Title for a Sidebar 

partintro


**** 
Discrete titles are useful for labeling large sidebar and admonition blocks.
****
sdsd

== Various
Various Questions about the Maritime Cloud

[discrete] 
=== Various 

==== Does the Maritime Cloud provide services such as weather information
No, the Maritime Cloud does not provide specific services such as weather information.
Instead it provides tools that allows for easy development of such services. For example,
the identity registry can be used to validate that a specific provider of weather information is actually who he says he is.
The service registry can be used to query about what kind of weather services are available in a given area. Or if someone wants to
be a provider of weather information. The description of which weather information standards to implement can be found in the service registry.
Finally, the MMS service can be used to push updated weather reports to ships.

////

==== Does the Maritime Cloud standardize services.
The Maritime Cloud does not mandata any specific process for development of service specifications.
It "just" allows organizations to register the outcome (in form of service specifications) in the Service Registry.
Providing a central place for service provides to find specifications they can implement.


////


==== Is the Maritime Cloud secure
In the long term the Maritime Cloud will use many of the same security technologies used by banks, e-commerce sites and governments. Messages sent to and from ships can be digitally signed. Communication channels can be encrypted. You will even be able to use biometric authentications methods such as fingerprints to sign documents and many other state of the art technologies. However, the current prototype does not support all these security features - yet. But they will be gradually added over the coming releases.


=== What are
The goals of the Maritime Cloud is to create 

Simplicity..
Developers can create XXX services in 1 hour.
It should be just as easy to 
A developer should be able to integrate with an existing service in a couple of hours.
The technologies in the Maritime Cloud complement each other.
Instead of being 



////
==== What is the Identity Registry
The identity registry is

The Maritime Industry has a rather unique problem shared with very few other industries in the world: Lack of bandwidth.


////
== MSDL

=== What is MSDL
MSDL is a standardized way of describing the services that can be used on the Maritime Cloud.
For example, instead of every company developing their own parser for an AIS message. 
The Maritime Cloud client can take a MSDL file and automatically generate the parser for you.
Avoiding the risk of developer mistakes and lowering the need for interoperability testing.

////
Long term, you will also be take to, for example, take a MSDL and generate the output you need in a S-100 specification.
////
=== Why didn't you just use XML and SOAP instead of MSDL and MMS
The short answer is bandwidth issues. Even compressed (zipped) XML still uses 3-4 times more bandwidth than an efficient binary encoding such as the one that we use. With Internet satellite prices of up to $30/MB and cost being a major barrier towards adoption. We believe a technology such as MSDL is the right choice.
There are other answers such that XML and SOAP is overly complex and most developers are moving towards simpler technologies such as combinations of REST and JSON. But bandwidth alone is the major driver.


